on:
  pull_request:
    types:
      - closed

name: Release Workflows

jobs:
  release_worfkflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: domix24/action-gitflow@main
        with:
          dev_branch: 'develop'
          main_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}