on:
  pull_request:
    types:
      - closed
    branches:
      - main

name: Release Workflows

jobs:
  release_worfkflow:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: domix24/action-gitflow@feature/automerge-develop
        with:
          dev_branch: 'develop'
          main_branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}